# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa1d69120fbdfe3811f95adc30e85e47f27462776ee27da52acf4e62a1b2b54487be29217937bbb260d7018fa2116db2dd9fbf29c9a01ea4b7a9a3a73c86d98d

test:
  secret_key_base: 75d44c54df84f41bc6fa0d61ad55c39610ec0126096d961fefb0bfab9d39b1eb458cdd0084217b4b5092d1d385efafbb13c8a4dfaab6afd5a29e9c91cc38d480

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
